### ISSUE TITLE
Better Handling for no config.rb or an empty config.rb

### ISSUE THREAD

**Issue by jeffgeorge** [clwdev/precip#14]
If a user hasn't filled out their config.rb or hasn't actually created one in the first place -- so like, the case of a completely fresh clone of precip -- they get a super unhelpful Ruby error:

```
/path/to/precip/Vagrantfile:35:in `concat': no implicit conversion of nil into Array (TypeError)
```

if a user hasn't made a config.rb yet, or hasn't filled it out with data:
- They shouldn't get any ruby errors
- It should print a big friendly red message to the terminal informing the user that they _really_ need to make a config.rb
- It should go ahead and build the box anyway, without any vhosts defined beyond the built-in one

**Comment by heathdutton** [comment]
Thank you for accounting for my ineptitude. :+1:
