### ISSUE TITLE
Increase VM memory

### ISSUE THREAD

**Issue by JamesDevware** [clwdev/precip#60]
With only 2GB of memory and a **large** database, MySQL locks are experienced relatively frequently. Increasing this to 4GB alleviates this issue.

Proposed solution is to either increase this in the vagrant file or allow this to be configured in config.rb Please let me know which you would prefer and I will raise a PR accordingly.

**Comment by jeffgeorge** [comment]
I think people would understandably lose their minds if we hardcoded it to 4G. I'd prefer a new `vm_memory` variable in `config.rb`, defaulting to 2048. 

You can model it after `vm_name`, see here:

https://github.com/clwdev/precip/blob/master/Vagrantfile#L9
https://github.com/clwdev/precip/blob/master/Vagrantfile#L113
https://github.com/clwdev/precip/blob/master/config.rb-dist#L99-L102

**Comment by jeffgeorge** [comment]
Oh, and while you're in there, update the comment to drop the apparently out of date reference to only ever seeing 1.5G used: https://github.com/clwdev/precip/blob/master/Vagrantfile#L131

**Comment by JamesDevware** [comment]
Sure will do!
